services:
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/static
    depends_on:
      - flask

  flask:
    build: ./app
    image: python
    container_name: flask_container
    command: gunicorn -b 0.0.0.0:5000 app:app
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # データはローカルにマウント
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL スクリプトのマウント  テーブルを作成  
  